name: Deno GitHub Workflow
on: workflow_dispatch
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Statement
        run: echo "Hello World"
  Demo:
    runs-on : ubuntu-latest
    steps:
      - name: Check S/W Version
        run: |
             java --version 
             mvn --version
      
